### ISSUE TITLE
0.3.7 Missing Release Package (.xpi)

### ISSUE THREAD

**Issue by historical-theology** [Niddrym/BlackboardInstructorEnhancements#1]
@Niddrym , please kindly package 0.3.7 (as an .xpi file), as with past releases.

By the way, after the ubiquitous extensions UBlock Origin and Midnight Lizard, this is the third extension that I install on a fresh full-size Web browser installation on a machine for work. It makes Blackboard less intolerable. For that, I owe you a huge "thank you."

Anyway, if 0.3.7 is going to be the last update, I understand, as I know that this is a lot of work. Yet, it would be nice to have it packaged :)

**Comment by Niddrym** [comment]
I've added the xpi to 0.3.7, it completely slipped my mind on the last release.

I haven't had as much time to add features as I'd like, but even with the features already in place I can't use the "regular" blackboard interface anymore.   

If you have any feature ideas/requests feel free to open more tickets.  No promises of course but I can try my best :)
